# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Emi01(models.Model):
    emi01codi = models.BigIntegerField(primary_key=True)
    gen01codi = models.IntegerField()
    emi01seri = models.ForeignKey('Emi03', models.DO_NOTHING, db_column='emi01seri')
    emi01clave = models.CharField(max_length=30)
    emi01anio = models.IntegerField()
    emi01mes = models.IntegerField()
    emi01dia = models.IntegerField()
    emi01fobl = models.DateField()
    emi01femi = models.DateField()
    emi01neli = models.IntegerField(blank=True, null=True)
    emi01feli = models.DateField(blank=True, null=True)
    emi01leli = models.CharField(max_length=12, blank=True, null=True)
    emi01fest = models.DateField(blank=True, null=True)
    emi01fpag = models.DateField(blank=True, null=True)
    emi01lpag = models.CharField(max_length=12, blank=True, null=True)
    emi01npag = models.CharField(max_length=30, blank=True, null=True)
    emi01vtot = models.DecimalField(max_digits=18, decimal_places=2)
    emi01inte = models.DecimalField(max_digits=18, decimal_places=2)
    emi01desc = models.DecimalField(max_digits=18, decimal_places=2)
    emi01reca = models.DecimalField(max_digits=18, decimal_places=2)
    emi01exo = models.CharField(max_length=1, blank=True, null=True)
    emi01esta = models.CharField(max_length=2)
    emi01titu = models.CharField(max_length=600, blank=True, null=True)
    emi01fcre = models.DateField()
    emi01lcre = models.CharField(max_length=12)
    emi01lmod = models.CharField(max_length=12, blank=True, null=True)
    emi0fmod = models.DateField(blank=True, null=True)
    emi01ncre = models.CharField(max_length=1, blank=True, null=True)
    emi01nrotit = models.CharField(max_length=150, blank=True, null=True)
    emi01pmer = models.CharField(max_length=250, blank=True, null=True)
    emi01evalo = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01coa = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01merca = models.BigIntegerField(blank=True, null=True)
    emi01iva = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01descmerca = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01msri = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01isri = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01motbaja = models.CharField(max_length=500, blank=True, null=True)
    emi01motlanc = models.CharField(max_length=500, blank=True, null=True)
    emi01planc = models.IntegerField(blank=True, null=True)
    emi01rlanc = models.CharField(max_length=500, blank=True, null=True)
    emi01crenta = models.IntegerField(blank=True, null=True)
    emi01nrotras = models.IntegerField(blank=True, null=True)
    emi01nrocoa = models.IntegerField(blank=True, null=True)
    pur01tmp = models.CharField(max_length=500, blank=True, null=True)
    gen01codi_recaud = models.IntegerField(blank=True, null=True)
    emi01codifpm = models.IntegerField(blank=True, null=True)
    emi01valorabonos = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01codianterior = models.BigIntegerField(blank=True, null=True)
    emi01fleyanciano = models.DateField(blank=True, null=True)
    emi01avaluosimpuesto = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01direccionpredio = models.CharField(max_length=500, blank=True, null=True)
    emi01parroquia = models.CharField(max_length=500, blank=True, null=True)
    emi01avaluoterreno = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01avaluoedif = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    textotmp = models.CharField(max_length=500, blank=True, null=True)
    emi01n1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01n2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01n3 = models.DecimalField(max_digits=18, decimal_places=6, blank=True, null=True)
    emi01n4 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01n5 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    emi01c1 = models.CharField(max_length=500, blank=True, null=True)
    emi01c2 = models.CharField(max_length=500, blank=True, null=True)
    emi01c3 = models.CharField(max_length=500, blank=True, null=True)
    emi01c4 = models.CharField(max_length=500, blank=True, null=True)
    emi01c5 = models.CharField(max_length=500, blank=True, null=True)
    emi01c6 = models.CharField(max_length=500, blank=True, null=True)
    emi01fcoa = models.DateField(blank=True, null=True)
    facelepro = models.CharField(max_length=10, blank=True, null=True)
    facelefec = models.DateField(blank=True, null=True)
    faceletdoc = models.CharField(max_length=20, blank=True, null=True)
    codproceso = models.IntegerField(blank=True, null=True)
    eminroct = models.IntegerField(blank=True, null=True)
    clave_sri = models.CharField(max_length=50, blank=True, null=True)
    estado_aut = models.CharField(max_length=1, blank=True, null=True)
    estado_sri = models.CharField(max_length=1, blank=True, null=True)
    fecha_auto = models.CharField(max_length=20, blank=True, null=True)
    nro_autorizacion = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'EMI01'


class Emi02(models.Model):
    emi02codi = models.BigIntegerField(primary_key=True)
    emi01codi = models.ForeignKey(Emi01, models.DO_NOTHING, db_column='emi01codi')
    emi04codi = models.ForeignKey('Emi04', models.DO_NOTHING, db_column='emi04codi')
    emi02vdet = models.DecimalField(max_digits=12, decimal_places=2)
    cdan = models.CharField(max_length=4, blank=True, null=True)
    nroct = models.IntegerField(blank=True, null=True)
    nrofac = models.CharField(max_length=20, blank=True, null=True)
    marcaborra = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'EMI02'


class Emi04(models.Model):
    emi04codi = models.IntegerField(primary_key=True)
    emi03codi = models.ForeignKey('Emi03', models.DO_NOTHING, db_column='emi03codi')
    emi05codi = models.IntegerField(blank=True, null=True)
    emi04desd = models.CharField(max_length=100)
    emi04obsl = models.CharField(max_length=200)
    emi04cemi = models.CharField(max_length=50)
    emi04cpag = models.CharField(max_length=50)
    emi04cbaj = models.CharField(max_length=50)
    emi04caju = models.CharField(max_length=30, blank=True, null=True)
    emi04lanc = models.CharField(max_length=1)
    emi04exo = models.CharField(max_length=1)
    emi04desc = models.CharField(max_length=1, blank=True, null=True)
    emi04reca = models.CharField(max_length=1, blank=True, null=True)
    emi04cint = models.CharField(max_length=1, blank=True, null=True)
    emi04acti = models.CharField(max_length=1, blank=True, null=True)
    emi04titucuent = models.CharField(max_length=30, blank=True, null=True)
    emi04ctaant = models.CharField(max_length=30, blank=True, null=True)
    emi04prannt = models.CharField(max_length=30, blank=True, null=True)
    emi04finicio = models.DateField(blank=True, null=True)
    emi04ffinal = models.DateField(blank=True, null=True)
    emi04opresenta = models.IntegerField(blank=True, null=True)
    emi04opagos = models.IntegerField(blank=True, null=True)
    emi04valorconst = models.DecimalField(max_digits=14, decimal_places=3, blank=True, null=True)
    emi04funcion = models.CharField(max_length=50, blank=True, null=True)
    emi04fondoa = models.CharField(max_length=1, blank=True, null=True)
    rpcuenta = models.CharField(max_length=100, blank=True, null=True)
    rccuenta = models.CharField(max_length=100, blank=True, null=True)
    rcuenta = models.CharField(max_length=100, blank=True, null=True)
    contracuenta_anteriores = models.CharField(max_length=50, blank=True, null=True)
    contracuenta_actual = models.CharField(max_length=50, blank=True, null=True)
    emi04servi = models.CharField(max_length=1, blank=True, null=True)
    emi04repr = models.CharField(max_length=2, blank=True, null=True)
    m_imp = models.CharField(max_length=1, blank=True, null=True)
    m_bom = models.CharField(max_length=1, blank=True, null=True)
    m_seg = models.CharField(max_length=1, blank=True, null=True)
    m_mej = models.CharField(max_length=1, blank=True, null=True)
    emi04codi_b = models.IntegerField(blank=True, null=True)
    emi04piva = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    emi04orcob = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'EMI04'


class Gen01(models.Model):
    gen01codi = models.IntegerField(primary_key=True)
    gen02codi = models.IntegerField()
    gen01ruc = models.CharField(max_length=20)
    gen01ced = models.CharField(max_length=14, blank=True, null=True)
    gen01tid = models.CharField(max_length=1)
    gen01nom = models.CharField(max_length=200, blank=True, null=True)
    gen01ape = models.CharField(max_length=200)
    gen01com = models.CharField(max_length=240)
    gen01dir = models.CharField(max_length=240)
    gen01telf = models.CharField(max_length=50, blank=True, null=True)
    gen01eciv = models.CharField(max_length=1)
    gen01sex = models.CharField(max_length=1)
    gen01revi = models.CharField(max_length=1, blank=True, null=True)
    gen01nco = models.CharField(max_length=100, blank=True, null=True)
    gen01lcrea = models.CharField(max_length=12)
    gen01fcre = models.DateField()
    gen01lmod = models.CharField(max_length=12, blank=True, null=True)
    gen01fmod = models.DateField(blank=True, null=True)
    gen01leli = models.CharField(max_length=12, blank=True, null=True)
    gen01feli = models.DateField(blank=True, null=True)
    gen01ccodi = models.IntegerField(blank=True, null=True)
    gen01cont = models.CharField(max_length=1, blank=True, null=True)
    gen01vota = models.CharField(max_length=30, blank=True, null=True)
    entidad_pago = models.CharField(max_length=50, blank=True, null=True)
    tipo_cuenta = models.CharField(max_length=1, blank=True, null=True)
    nro_cuenta = models.CharField(max_length=50, blank=True, null=True)
    autorizacion = models.CharField(max_length=10, blank=True, null=True)
    serie = models.CharField(max_length=6, blank=True, null=True)
    fcaducidad = models.DateField(blank=True, null=True)
    gen01email = models.CharField(max_length=100, blank=True, null=True)
    gen01tipo = models.CharField(max_length=30, blank=True, null=True)
    gen01fnac = models.DateField(blank=True, null=True)
    gen01disca = models.CharField(max_length=10, blank=True, null=True)
    gen01cony = models.DecimalField(max_digits=22, decimal_places=8, blank=True, null=True)
    gen01repleg = models.DecimalField(max_digits=22, decimal_places=8, blank=True, null=True)
    gen01lresi = models.CharField(max_length=15, blank=True, null=True)
    gen01cyruc = models.CharField(max_length=16, blank=True, null=True)
    gen01cycom = models.CharField(max_length=240, blank=True, null=True)
    gen01cydisca = models.CharField(max_length=10, blank=True, null=True)
    gen01cyfnac = models.DateField(blank=True, null=True)
    gen01cynom = models.CharField(max_length=100, blank=True, null=True)
    gen01cyape = models.CharField(max_length=100, blank=True, null=True)
    gen01codi_mun = models.DecimalField(max_digits=22, decimal_places=8, blank=True, null=True)
    gen01deb = models.CharField(max_length=10, blank=True, null=True)
    gen01tpct = models.CharField(max_length=20, blank=True, null=True)
    gen01nrocta = models.CharField(max_length=20, blank=True, null=True)
    banc01codi = models.DecimalField(max_digits=22, decimal_places=8, blank=True, null=True)
    gen01fautdeb = models.DateField(blank=True, null=True)
    gen01lautodeb = models.CharField(max_length=12, blank=True, null=True)
    gen01docauto = models.CharField(max_length=100, blank=True, null=True)
    gen01imgdocu = models.BinaryField(blank=True, null=True)
    gen01provi = models.CharField(max_length=100, blank=True, null=True)
    gen01parro = models.CharField(max_length=100, blank=True, null=True)
    gen01interseccion = models.CharField(max_length=100, blank=True, null=True)
    gen01nrocasa = models.CharField(max_length=20, blank=True, null=True)
    gen01nacion = models.CharField(max_length=5, blank=True, null=True)
    gen01ciudad = models.CharField(max_length=50, blank=True, null=True)
    gen01barrio = models.CharField(max_length=50, blank=True, null=True)
    gen01telf2 = models.CharField(max_length=30, blank=True, null=True)
    gen01referen = models.CharField(max_length=300, blank=True, null=True)
    gen01ape_cy = models.CharField(max_length=50, blank=True, null=True)
    gen01ced_cy = models.CharField(max_length=15, blank=True, null=True)
    gen01com_cy = models.CharField(max_length=105, blank=True, null=True)
    gen01fnac_cy = models.DateField(blank=True, null=True)
    gen01nom_cy = models.CharField(max_length=50, blank=True, null=True)
    gen01cedcony = models.CharField(max_length=13, blank=True, null=True)
    gen01conyu = models.CharField(max_length=300, blank=True, null=True)
    gen01etnia = models.CharField(max_length=30, blank=True, null=True)
    gen01oblicont = models.CharField(max_length=5, blank=True, null=True)
    gen01fmuere = models.CharField(max_length=20, blank=True, null=True)
    consultadodinardap = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'GEN01'
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Emi03(models.Model):
    emi03codi = models.IntegerField(primary_key=True)
    emi03des = models.CharField(max_length=80)
    emi03nota = models.CharField(max_length=500)
    emi03tipo = models.CharField(max_length=1)
    emi03fing = models.DateField()
    emi03fter = models.DateField(blank=True, null=True)
    emi03tpem = models.CharField(max_length=1)
    emi03pant = models.CharField(max_length=8, blank=True, null=True)
    emi03cond = models.CharField(max_length=1)
    emi03inte = models.CharField(max_length=1, blank=True, null=True)
    emi03reca = models.CharField(max_length=1, blank=True, null=True)
    emi03desc = models.CharField(max_length=1)
    emi03pred = models.CharField(max_length=1, blank=True, null=True)
    emi03bloq = models.CharField(max_length=1, blank=True, null=True)
    emi03reporte = models.CharField(max_length=50, blank=True, null=True)
    emi03adicional = models.CharField(max_length=1, blank=True, null=True)
    emi03vadicional = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    emi03tipo_seleccion = models.CharField(max_length=1, blank=True, null=True)
    emio3presenta = models.CharField(max_length=1, blank=True, null=True)
    ctas01codi = models.CharField(max_length=100, blank=True, null=True)
    ruta = models.CharField(max_length=250, blank=True, null=True)
    emi03iva = models.CharField(max_length=50, blank=True, null=True)
    emi03piva = models.DecimalField(max_digits=14, decimal_places=2, blank=True, null=True)
    emi03tiporepo = models.CharField(max_length=2, blank=True, null=True)
    emi03seq = models.BigIntegerField(blank=True, null=True)
    emi03serie = models.CharField(max_length=6, blank=True, null=True)
    emi03seqnc = models.BigIntegerField(blank=True, null=True)
    emi03seqdeb = models.BigIntegerField(blank=True, null=True)
    seg04codi = models.CharField(max_length=30, blank=True, null=True)
    emi03directo = models.CharField(max_length=1, blank=True, null=True)
    emi03reportecp = models.CharField(max_length=20, blank=True, null=True)
    emi03reportes = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'EMI03'
